service: notebook-api
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  profile: ${env:AWS_PROFILE}
  region: eu-north-1
  iam:
    role: ${env:AWS_IAM_ROLE}
  environment:
    DYNAMO_DB_TABLE: ${env:DYNAMO_DB_TABLE}
    APP_KEY: ${env:APP_KEY}

# APP_KEY -> USE KMS KEY OR AWS.SSM
      
plugins:
  - serverless-webpack

package: 
  individually: true

functions:
  getNotes:
    handler: api/get/notes.handler
    events:
      - httpApi:
          path: '/api/notes'
          method: GET
  getNote:
    handler: api/get/note.handler
    events:
      - httpApi:
          path: '/api/note/{id}'
          method: GET
  postNotes:
    handler: api/post/notes.handler
    events:
      - httpApi:
          path: '/api/notes'
          method: POST
  putNotes:
    handler: api/put/notes.handler/{id}
    events:
      - httpApi:
          path: '/api/notes'
          method: PUT
  deleteNotes:
    handler: api/delete/notes.handler
    events:
      - httpApi:
          path: '/api/notes{id}'
          method: DELETE
  signup:
    handler: api/user/signup.handler 
    events:
      - httpApi:
          path: '/api/user/signup'
          method: POST
  login:
    handler: api/user/login.handler 
    events:
      - httpApi:
          path: '/api/user/login'
          method: POST
resources:
 Resources:
    teamDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: NOTES
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST